name: Pulumi preview
"on":
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
    run_pulumi_update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pulumi/auth-actions@v1
              with:
                organization: piers-rbac-test
                scope: team:GitHubTeam
                requested-token-type: urn:pulumi:token-type:access_token:team
            - uses: pulumi/actions@v6
              with:
                command: preview
                stack-name: piers-rbac-test/dev 
            - uses: pulumi/actions@v6
              with:
                command: update
                stack-name: piers-rbac-test/dev 